### ISSUE TITLE
--wait option

### ISSUE THREAD

**Issue by recoilstv** [Anthony96922/mpxgen#2]
Hi, Anthony! Please tell me, the function "wait@ is excluded from the MPXGEN?

**Comment by Anthony96922** [comment]
It now always waits for new audio. Do you still want the toggle back?

**Comment by recoilstv** [comment]
> It now always waits for new audio. Do you still want the toggle back?

Yes, that would be great! If ffmpeg freezes, only the carrier with no sound remains on the air.

**Comment by Anthony96922** [comment]
The sound input code has been changed so if there is nothing in the input the audio goes silent but the RDS encoder keeps running.

**Comment by recoilstv** [comment]
I'm sorry, I misspelled it. I want to use not only RDS, but also MPX. Therefore, if only **mpxgen** remains on the input after the sound disappears, this will be a problem. If you return the flag, this may be the solution, and I can control the behavior of **mpxgen** when the sound disappears.

**Comment by Anthony96922** [comment]
I added it back in the latest commit. 82f5f79
